server:
  servlet:
    context-path: /cp
  port: 8866
spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  resources:
    static-locations: classpath:/templates/, classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/,file:${receivePath}
projectPath: /ext/app/cosplay
receivePath: ${projectPath}/images/
